name: Deploy Indexer to ECR

on:
  push:
    branches:
      - feat/topic-cicd-tan
    paths:
      - indexer/**

env:
  REPOSITORY_NAME: indexer

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          cd ${{ env.REPOSITORY_NAME }}
          echo ${{secrets.CREDENTIALS_JSON}} > services/credentials.json
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT

  deploy:
    needs: build # Run deploy only after the build job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          port: 22
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ needs.build.outputs.registry }}
            docker pull ${{ needs.build.outputs.registry }}/${{ env.REPOSITORY_NAME }}:latest
            docker compose down
            docker rmi ${{ needs.build.outputs.registry }}/${{ env.REPOSITORY_NAME }}:latest
            docker compose up -d
